version: 0.0
Resources:
  - TargetService:
      Type: AWS::ECS::Service
      Properties:
        TaskDefinition: <arn:aws:ecs:eu-west-3:199051453468:task-definition/talsa-nginx-td:1>
        LoadBalancerInfo:
          ContainerName: "nginx"
          ContainerPort: 80
